"""add agent approvals and autonomy policy

Revision ID: 155c3c720996
Revises: d4e5f6a7b8c9
Create Date: 2026-09-20 03:09:00.467293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '155c3c720996'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_approvals_action_type'), 'agent_approvals', ['action_type'], unique=False)
    op.create_index(op.f('ix_agent_approvals_created_at'), 'agent_approvals', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_approvals_expires_at'), 'agent_approvals', ['expires_at'], unique=False)
    op.create_index(op.f('ix_agent_approvals_job_id'), 'agent_approvals', ['job_id'], unique=False)
    op.create_index(op.f('ix_agent_approvals_run_id'), 'agent_approvals', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_approvals_status'), 'agent_approvals', ['status'], unique=False)
    op.create_index(op.f('ix_agent_approvals_user_id'), 'agent_approvals', ['user_id'], unique=False)
    op.add_column(
        'preferences',
        sa.Column(
            'autonomy_policy',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            server_default=sa.text(
                '\'{"search": "autonomous", "analyze": "autonomous", "save_job": "approval_required", "dismiss_job": "approval_required", "update_pipeline_status": "approval_required"}\'::jsonb'
            ),
        ),
    )
    op.alter_column('preferences', 'experience_level',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'ALL'::character varying"))
    op.alter_column('preferences', 'preferred_locations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('preferences', 'role_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'ALL'::character varying"))
    op.alter_column('preferences', 'source_boards',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text('\'["LINKEDIN", "NAUKRI", "INTERNSHALA"]\'::jsonb'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('preferences', 'source_boards',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text('\'["LINKEDIN", "NAUKRI", "INTERNSHALA"]\'::jsonb'))
    op.alter_column('preferences', 'role_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'ALL'::character varying"))
    op.alter_column('preferences', 'preferred_locations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('preferences', 'experience_level',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'ALL'::character varying"))
    op.drop_column('preferences', 'autonomy_policy')
    op.drop_index(op.f('ix_agent_approvals_user_id'), table_name='agent_approvals')
    op.drop_index(op.f('ix_agent_approvals_status'), table_name='agent_approvals')
    op.drop_index(op.f('ix_agent_approvals_run_id'), table_name='agent_approvals')
    op.drop_index(op.f('ix_agent_approvals_job_id'), table_name='agent_approvals')
    op.drop_index(op.f('ix_agent_approvals_expires_at'), table_name='agent_approvals')
    op.drop_index(op.f('ix_agent_approvals_created_at'), table_name='agent_approvals')
    op.drop_index(op.f('ix_agent_approvals_action_type'), table_name='agent_approvals')
    op.drop_table('agent_approvals')
    # ### end Alembic commands ###
